version: '3.9'
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: guitar-shop_mongodb
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - guitar-shop_data:/data/db

  db_ui:
    image: mongo-express:latest
    restart: always
    container_name: guitar-shop_mongo_express
    ports:
      - 8081:8081
    env_file:
      - .env

volumes:
  guitar-shop_data:
