# Гитары
## Гитара по идентификатору

GET http://localhost:4000/products/65107d9fc431bfb17ee9bbbf HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NTEwMWJlMzA3YTg3ZjY2MmQxYjFjYjEiLCJpYXQiOjE2OTU1NTQ1NTQsImV4cCI6MTY5NTcyNzM1NH0._7levRPkoncsuwl7Rpl5Gkf3l6C5ZrhHXkbGXUrB9oE

###

## Добавление новой гитары

POST http://localhost:4000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NTEwMWJlMzA3YTg3ZjY2MmQxYjFjYjEiLCJpYXQiOjE2OTU1NTQ1NTQsImV4cCI6MTY5NTcyNzM1NH0._7levRPkoncsuwl7Rpl5Gkf3l6C5ZrhHXkbGXUrB9oE

{
  "title": "Крутая гитара",
  "description": "Подойдет для выступлений",
  "createdAt": "2022-05-12T11:56:37.573Z",
  "image": "catalog-product-0.png",
  "type": "Укулеле",
  "article": "QWERTY1234",
  "numberOfStrings": "12",
  "price": 300
}

###

###

## Обновление существующей гитары

put  http://localhost:4000/products/65107d9fc431bfb17ee9bbbf HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NTEwMWJlMzA3YTg3ZjY2MmQxYjFjYjEiLCJpYXQiOjE2OTU1NTQ1NTQsImV4cCI6MTY5NTcyNzM1NH0._7levRPkoncsuwl7Rpl5Gkf3l6C5ZrhHXkbGXUrB9oE

{
  "title": "Не очень крутая гитара",
  "description": "Не подойдет для выступлений",
  "image": "catalog-product-1.png",
  "createdAt": "2022-05-12T11:56:37.573Z",
  "type": "Электрогитара",
  "article": "1234QWERTY",
  "numberOfStrings": "7",
  "price": 5505
}

###

## Удаление существующей гитары

DELETE http://localhost:4000/products/65101b0757fb681835aab81c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NTEwMWJlMzA3YTg3ZjY2MmQxYjFjYjEiLCJpYXQiOjE2OTU1NTQ1NTQsImV4cCI6MTY5NTcyNzM1NH0._7levRPkoncsuwl7Rpl5Gkf3l6C5ZrhHXkbGXUrB9oE

###

## Гитары в колличестве указанном в параметре limit

GET http://localhost:4000/products?limit=60 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZlbGl1Z2luQG1haWwubmV0IiwiaWQiOiI2NTEwMWJlMzA3YTg3ZjY2MmQxYjFjYjEiLCJpYXQiOjE2OTU1NTQ1NTQsImV4cCI6MTY5NTcyNzM1NH0._7levRPkoncsuwl7Rpl5Gkf3l6C5ZrhHXkbGXUrB9oE

###

## Изменение изображения гитары

POST http://localhost:4000/products/65101b0b57fb681835aab820/image HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQG1haWwubmV0IiwiaWQiOiI2NTEwOTRmMjgxOWE1MmFkMjRmODQ2MjQiLCJpYXQiOjE2OTU3Mjc1MzAsImV4cCI6MTY5NTkwMDMzMH0.BObAk4yE7t4OCs3dblli_9RM1SqiEdoUTmd06RUfueA
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="catalog-product-0.png"
Content-Type: image/png

< frontend/project/public/img/content/catalog-product-0.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
