export const LENGTH_CONSTANTS = {
  MIN_LENGTH_TITLE: 10,
  MAX_LENGTH_TITLE: 100,
  MIN_LENGTH_DESCRIPTION: 20,
  MAX_LENGTH_DESCRIPTION: 1024,
  MIN_LENGTH_ARTICLE: 5,
  MAX_LENGTH_ARTICLE: 40,
  MIN_LENGTH_PRICE: 100,
  MAX_LENGTH_PRICE: 1000000,
};

export const COUNT_CONSTANTS = {
  DEFAULT_PRODUCTS_COUNT: 7
};
